import express from "express";
import multer from "multer";
import path from "path";
import fs from "fs";
import pdf from "pdf-parse";
import Report from "../models/Report.js";
import { requireAuth } from "../middleware/auth.js";
import { getDemoResults, parseReportText } from "../services/reportParser.js";
import { fetchMedicalExplanation, wellnessGuidance } from "../medicalLookup.js";

const router = express.Router();
const uploadDir = path.resolve("uploads");
fs.mkdirSync(uploadDir, { recursive: true });

const storage = multer.diskStorage({
  destination: (_, __, cb) => cb(null, uploadDir),
  filename: (_, file, cb) => {
    const safe = file.originalname.replace(/[^a-zA-Z0-9._-]/g, "_");
    cb(null, `${Date.now()}-${safe}`);
  }
});

const upload = multer({
  storage,
  // Medical reports can be multi-page PDFs with embedded tables/images.
  // Keep a practical ceiling while avoiding rejection of larger legitimate reports.
  limits: { fileSize: 25 * 1024 * 1024 },
  fileFilter: (_, file, cb) => {
    const isPdf =
      file.mimetype === "application/pdf" ||
      /\.pdf$/i.test(String(file.originalname || ""));
    cb(null, isPdf);
  }
});

function renderPage(pageData) {
  return pageData
    .getTextContent({
      normalizeWhitespace: false,
      disableCombineTextItems: false
    })
    .then((textContent) => {
      const rows = [];

      for (const item of textContent.items) {
        const text = String(item.str || "").trim();
        if (!text) continue;

        const x = Number(item.transform?.[4] || 0);
        const y = Math.round(Number(item.transform?.[5] || 0));

        let row = rows.find((candidate) => Math.abs(candidate.y - y) <= 1);
        if (!row) {
          row = { y, items: [] };
          rows.push(row);
        }

        row.items.push({ x, text });
      }

      rows.sort((a, b) => b.y - a.y);

      return rows
        .map((row) =>
          row.items
            .sort((a, b) => a.x - b.x)
            .map((item) => item.text)
            .join(" ")
            .replace(/\s+/g, " ")
            .trim()
        )
        .filter(Boolean)
        .join("\n");
    });
}

async function enrichResults(results) {
  return Promise.all(
    results.map(async (result) => {
      // Once a result already contains a dynamic MedlinePlus explanation,
      // source URL, purpose and wellness guidance, reuse it instead of
      // repeatedly querying MedlinePlus every time the report is opened.
      // Older records stored a generic wellness sentence. Current HealthLens
      // wellness guidance is always category + status specific and uses the
      // bullet format generated by medicalLookup.js. Treat anything else as
      // stale so opening an old report repairs it automatically.
      const wellnessText = String(result.wellness || "").trim();
      const legacyWellness =
        !wellnessText ||
        /^For context about this result/i.test(wellnessText) ||
        /^This result is within the sample report/i.test(wellnessText);

      if (
        !legacyWellness &&
        Number(result.wellnessVersion) >= 7 &&
        result.explanation &&
        result.why &&
        result.professional &&
        result.statusContext
      ) {
        return result;
      }

      const lookup = await fetchMedicalExplanation(result.testName, result.status);

      // Wellness guidance is generated locally from the actual terminology and
      // report status. It must never disappear just because MedlinePlus is
      // unavailable or an older report was saved with a generic sentence.
      const wellnessResult = await wellnessGuidance(
        result.testName,
        result.status,
        lookup?.title ? lookup : { title: result.testName }
      );
      if (!lookup) {
        return {
          ...result,
          wellness: wellnessResult?.text || result.wellness || "",
          wellnessSourceUrl: wellnessResult?.sourceUrl || "",
          wellnessSourceTitle: wellnessResult?.sourceTitle || "",
          wellnessVersion: 7,
          statusContext: await (async () => {
            const refreshed = await fetchMedicalExplanation(result.testName, result.status);
            return refreshed?.statusContext || result.statusContext || "";
          })()
        };
      }

      return {
        ...result,
        explanation: lookup.explanation || result.explanation,
        medicalTitle: lookup.title || result.testName,
        why: lookup.why || result.why || "",
        wellness: wellnessResult?.text || lookup.wellness || result.wellness || "",
        wellnessSourceUrl: wellnessResult?.sourceUrl || lookup.wellnessSourceUrl || result.wellnessSourceUrl || "",
        wellnessSourceTitle: wellnessResult?.sourceTitle || lookup.wellnessSourceTitle || result.wellnessSourceTitle || "",
        wellnessVersion: 7,
        professional: lookup.professional || result.professional || "",
        statusContext: lookup.statusContext || result.statusContext || "",
        medicalSource: lookup.source || result.medicalSource || "MedlinePlus",
        medicalSourceOrganization: lookup.sourceOrganization || result.medicalSourceOrganization || "National Library of Medicine",
        medicalSourceUrl: lookup.sourceUrl || result.medicalSourceUrl || ""
      };
    })
  );
}

async function parsePdfFile(filePath) {
  const buffer = fs.readFileSync(filePath);

  // Use the layout-aware renderer first. Some PDFs expose their text in a
  // different order, so also try pdf-parse's default extraction and keep the
  // extraction that gives us more usable text.
  const rendered = await pdf(buffer, { pagerender: renderPage });
  let extractedText = String(rendered.text || "");

  if (extractedText.replace(/\s+/g, "").length < 120) {
    try {
      const plain = await pdf(buffer);
      if (String(plain.text || "").length > extractedText.length) {
        extractedText = String(plain.text || "");
      }
    } catch (fallbackError) {
      console.warn("Secondary PDF text extraction skipped:", fallbackError.message);
    }
  }

  const results = await parseReportText(extractedText);

  if (!results.length) {
    return [];
  }

  return enrichResults(results);
}

function findLegacyUploadedPdf(report) {
  if (report.storedFileName) {
    const storedPath = path.join(uploadDir, report.storedFileName);
    if (fs.existsSync(storedPath)) return storedPath;
  }

  const safeOriginalName = String(report.fileName || "")
    .replace(/[^a-zA-Z0-9._-]/g, "_");

  if (!safeOriginalName) return null;

  const matches = fs
    .readdirSync(uploadDir)
    .filter((name) => name.endsWith(`-${safeOriginalName}`))
    .map((name) => ({
      name,
      path: path.join(uploadDir, name),
      timestamp: Number(name.split("-")[0]) || 0
    }))
    .filter((item) => fs.existsSync(item.path))
    .sort((a, b) => b.timestamp - a.timestamp);

  return matches[0]?.path || null;
}

router.get("/", requireAuth, async (req, res, next) => {
  try {
    const reports = await Report.find({ userId: req.userId }).sort({ uploadDate: -1 });
    res.json({ reports });
  } catch (e) {
    next(e);
  }
});

router.get("/:id", requireAuth, async (req, res, next) => {
  try {
    const report = await Report.findOne({ _id: req.params.id, userId: req.userId });
    if (!report) return res.status(404).json({ message: "Report not found." });

    // Older HealthLens reports may have been saved before the corrected parser
    // existed. If the original PDF is still in uploads, transparently reparse
    // it once so the existing report also receives the corrected structure.
    if (report.fileType === "application/pdf" && report.source !== "demo" && !report.storedFileName) {
      const pdfPath = findLegacyUploadedPdf(report);

      if (pdfPath) {
        try {
          const correctedResults = await parsePdfFile(pdfPath);

          if (correctedResults.length) {
            report.results = correctedResults;
            report.storedFileName = path.basename(pdfPath);
            await report.save();
          }
        } catch (refreshError) {
          console.warn("Legacy report refresh skipped:", refreshError.message);
        }
      }
    }

    // Refresh the short, plain-language medical explanations as well.
    // This also corrects reports saved with an older MedlinePlus result.
    if (report.results?.length) {
      const refreshedResults = await enrichResults(report.results);
      report.results = refreshedResults;
      await report.save();
    }

    res.json({ report });
  } catch (e) {
    next(e);
  }
});

router.delete("/:id", requireAuth, async (req, res, next) => {
  try {
    const report = await Report.findOneAndDelete({ _id: req.params.id, userId: req.userId });
    if (!report) return res.status(404).json({ message: "Report not found." });
    res.json({ message: "Report deleted." });
  } catch (e) {
    next(e);
  }
});

router.post("/demo", requireAuth, async (req, res, next) => {
  try {
    const report = await Report.create({
      userId: req.userId,
      fileName: "HealthLens_Demo_Report.pdf",
      fileType: "application/pdf",
      source: "demo",
      reportDate: new Date(),
      results: getDemoResults()
    });

    res.status(201).json({ report });
  } catch (e) {
    next(e);
  }
});

router.post("/upload", requireAuth, upload.single("report"), async (req, res, next) => {
  try {
    if (!req.file) {
      return res.status(400).json({ message: "Please select a PDF, PNG or JPG report." });
    }

    const isPdf =
      req.file.mimetype === "application/pdf" ||
      /\.pdf$/i.test(String(req.file.originalname || ""));

    if (!isPdf) {
      return res.status(400).json({
        message: "Please upload a PDF medical report."
      });
    }

    let results = await parsePdfFile(req.file.path);

    if (!results.length) {
      return res.status(422).json({
        message: "This PDF was accepted, but HealthLens could not find readable laboratory results with reference ranges. Please use a PDF with selectable report text or a clearly readable lab-results table."
      });
    }

    const report = await Report.create({
      userId: req.userId,
      fileName: req.file.originalname,
      storedFileName: req.file.filename,
      fileType: req.file.mimetype,
      source: "upload",
      reportDate: new Date(),
      results
    });

    res.status(201).json({
      report,
      notice: "Report processed using the values and reference information extracted from the uploaded report."
    });
  } catch (e) {
    next(e);
  }
});

export default router;
